/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated/transfers'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedBetsRouteImport } from './routes/_authenticated/bets'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'
import { Route as AuthenticatedTransfersImportRouteImport } from './routes/_authenticated/transfers.import'
import { Route as AuthenticatedBetsImportRouteImport } from './routes/_authenticated/bets.import'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBetsRoute = AuthenticatedBetsRouteImport.update({
  id: '/bets',
  path: '/bets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransfersImportRoute =
  AuthenticatedTransfersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedTransfersRoute,
  } as any)
const AuthenticatedBetsImportRoute = AuthenticatedBetsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedBetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bets': typeof AuthenticatedBetsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/transfers': typeof AuthenticatedTransfersRouteWithChildren
  '/bets/import': typeof AuthenticatedBetsImportRoute
  '/transfers/import': typeof AuthenticatedTransfersImportRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bets': typeof AuthenticatedBetsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/transfers': typeof AuthenticatedTransfersRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/bets/import': typeof AuthenticatedBetsImportRoute
  '/transfers/import': typeof AuthenticatedTransfersImportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bets': typeof AuthenticatedBetsRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bets/import': typeof AuthenticatedBetsImportRoute
  '/_authenticated/transfers/import': typeof AuthenticatedTransfersImportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/bets'
    | '/history'
    | '/setup'
    | '/transfers'
    | '/bets/import'
    | '/transfers/import'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/accounts'
    | '/analytics'
    | '/bets'
    | '/history'
    | '/setup'
    | '/transfers'
    | '/'
    | '/bets/import'
    | '/transfers/import'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accounts'
    | '/_authenticated/analytics'
    | '/_authenticated/bets'
    | '/_authenticated/history'
    | '/_authenticated/setup'
    | '/_authenticated/transfers'
    | '/_authenticated/'
    | '/_authenticated/bets/import'
    | '/_authenticated/transfers/import'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bets': {
      id: '/_authenticated/bets'
      path: '/bets'
      fullPath: '/bets'
      preLoaderRoute: typeof AuthenticatedBetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transfers/import': {
      id: '/_authenticated/transfers/import'
      path: '/import'
      fullPath: '/transfers/import'
      preLoaderRoute: typeof AuthenticatedTransfersImportRouteImport
      parentRoute: typeof AuthenticatedTransfersRoute
    }
    '/_authenticated/bets/import': {
      id: '/_authenticated/bets/import'
      path: '/import'
      fullPath: '/bets/import'
      preLoaderRoute: typeof AuthenticatedBetsImportRouteImport
      parentRoute: typeof AuthenticatedBetsRoute
    }
  }
}

interface AuthenticatedBetsRouteChildren {
  AuthenticatedBetsImportRoute: typeof AuthenticatedBetsImportRoute
}

const AuthenticatedBetsRouteChildren: AuthenticatedBetsRouteChildren = {
  AuthenticatedBetsImportRoute: AuthenticatedBetsImportRoute,
}

const AuthenticatedBetsRouteWithChildren =
  AuthenticatedBetsRoute._addFileChildren(AuthenticatedBetsRouteChildren)

interface AuthenticatedTransfersRouteChildren {
  AuthenticatedTransfersImportRoute: typeof AuthenticatedTransfersImportRoute
}

const AuthenticatedTransfersRouteChildren: AuthenticatedTransfersRouteChildren =
  {
    AuthenticatedTransfersImportRoute: AuthenticatedTransfersImportRoute,
  }

const AuthenticatedTransfersRouteWithChildren =
  AuthenticatedTransfersRoute._addFileChildren(
    AuthenticatedTransfersRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBetsRoute: typeof AuthenticatedBetsRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBetsRoute: AuthenticatedBetsRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
