// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okdgqeezzrusfrxzufkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZGdxZWV6enJ1c2ZyeHp1ZmtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEzNDcwMDIsImV4cCI6MjA5NjkyMzAwMn0.aBDvmGrSKDckqbZcEMqzFXIgJ36kXVkiH-EKqt0UECw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});